spring:
  application:
    name: Profile-Service

  datasource:
    url: jdbc:mysql://localhost:3306/profiledb
    username: root
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:8087}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

secret:
  header:
    key: ${SECRET_HEADER_KEY}
